### ISSUE TITLE
Mobile Viewport Meta Tag

### ISSUE THREAD

**Issue by bhk1019** [rahavassaf/bootcamp-splurty#1]
Nice work deploying your app to production. Though your site looks great on my computer, on mobile, it could look a lot better.

I’ve marked a good spot in your code here to add a “meta tag” that should help make your app look good on all mobile devices as well.

This is a great opportunity for you to do some research on a “viewport meta tag” that will solve this issue. Take some time to Google it, and try implementing it on your own. Once you’ve figured it out, let me know in the comments below. :)

https://github.com/rahavassaf/bootcamp-splurty/blob/2d5cbaa1b13320cb6922f4b88b5221174a7d15ea/app/views/layouts/application.html.erb#L7

**Comment by rahavassaf** [comment]
Hi Ben!

Please review the commit referenced above. This version is now live on heroku.
